### PR TITLE
Cancel planning

### PR DESCRIPTION
**Pull request by mharsat**
And mock events

### CODE REVIEW

**Review by idosavion — APPROVED** [review]
looks good, I think that some of the events should already appear in the past fragment, right?

**Comment by AmitSilber** [comment]
לא לא לא לא... 
אי אפשר סתם למחוק

**Review by mfocshaner — CHANGES_REQUESTED** [review]
don't merge unless Amit approves.

**Comment by mharsat** [comment]
> don't merge unless Amit approves.

Obviously didn't mean to

**Comment by mfocshaner** [comment]
yeah i know, just wanted to make sure this is not accidentally merged

**Pull request closed without merging**
